apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.31.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/klusterweb-default: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: kluster
            - name: MYSQL_ROOT_HOST
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: rlaxogjs8312
            - name: TZ
              value: Asia/Seoul
          image: mysql/mysql-server:8.0
          name: database
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-init.d
      restartPolicy: Always
      volumes:
        - name: mysql-init.d
          persistentVolumeClaim:
            claimName: mysql-init.d
status: {}
