apiVersion: apps/v1
kind: Deployment
metadata:
  name: klusterweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klusterweb
  template:
    metadata:
      labels:
        app: klusterweb
    spec:
      containers:
        - name: klusterweb
          image: jakeheon/klusterweb:latest # 도커 이미지 이름과 버전을 적절하게 변경
          ports:
            - containerPort: 8080