apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert --controller statefulset
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  serviceName: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/klusterweb-default: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: kluster
            - name: MYSQL_ROOT_PASSWORD
              value: rlaxogjs8312
          image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: ./mysqlinit
              name: mysqlinit
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: mysqlinit
        name: mysqlinit
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-path"
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  availableReplicas: 0
  replicas: 0
