apiVersion: v1
kind: Service
metadata:
  name: klusterweb
spec:
  selector:
    app: klusterweb
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
