apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml --namespace=server --controller statefulset convert
    kompose.version: 1.31.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-app
  name: spring-app
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-app
  serviceName: spring-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/klusterweb-default: "true"
        io.kompose.service: spring-app
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/kluster
          image: jakeheon/klusterweb
          name: spring-app
          ports:
            - containerPort: 8080
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  availableReplicas: 0
  replicas: 0
