
name: CI with Gradle

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0

    - name: Docker build & push to docker repo
      run: |
          docker login -u jakeheon -p rlaxogjs8312@
          docker build -t jakeheon/testtesst122 -f Dockerfile .
          docker push jakeheon/testtesst122

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Notify Server
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"status":"completed"}' http://54.180.150.131/github/notify

