spring:
  profiles:
    include: secure
  datasource:
    url: jdbc:mysql://mysql:3306/kluster  # MySQL 호스트 및 포트
    username: root
    password: rlaxogjs8312
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher
jwt:
  secret: ENC(1mPRNzjXY+Uha2424+Zwk14A8rln8cRI7y+7/mbD+fDPQ7BuoOeaXYs12NxOJ66d38UQSCDTBszml6lBtf8eEQ==)
jenkins:
  url: jenkins-url
  secret-key: jenkins-secret-key
github:
  access-token: ENC(JTR6X87H+WFajH+mLgRK9bfcZogx34+fyrViAXvdazIXplkWJhOUPVzcim7i1PnQMSrai1LDV3w=)
univcert:
  api:
    key: ENC(mEC2ThOsBweDr/jxdhV+r9IZ4HB005ZTWRUfIw8U4Sfqas2tBbJ34nna2jLJhoy6)
config:
  kubernetes:
    url: https://kluster.iptime.org:6443
    token: ENC(hewVdv+9/ps/Go+TCiRRrlC+Ci/hAGKip5wmvOjb3Ez0SPPTzViDOf2k0icJunG+v50pBKth9PFIxUBjyJSfLeqrYDFZ7BFmBNtmtBMQM0oi1WBRTOWuxX3aRQItt5G4lrBFyg4M/Jqnn8aFRTjH7FY0bZZPkfjUg3p2RgD/NXl6CFtrcHCcD1vDcBN+Y0EB6vyBbi88dgL005An4HauMHYQ7I5wWBJzei7G8ps5rDV3JC6oEFextpX/txJIUuYlk0jigOmAfqYGbWur0U/ewD3pRCO13pmtp7LTmgHwuaDTD5DEqJH4qk00lvlCmy+RiReYkeErCRjIwoPeXBdvq30v2OsW09u36u8CL+ihZWk5YokDbrg8JC7/thiU60M9cuafJi76LB4gR07U08F6epSB4+KwO99PxkF3iCkll9S3DCHNMUMk1QWjF8IGsbP51H8kMILJY+GTfMectzeQ8SeqhEGNy3y+yEVsQstX18Yyw2f++G5sKo36uKMgZbO6v+/bY6AX2ES1OvPOH1Kg2rpNAvxEUnz8lTp+Ax1bLtkwhPph20+szdyY57UWvQdxpAlr54mmAIhdfAImvzFr3sRsVS8gIsmfMj+oqUeMxQXmXxy4fEE9ssQp5oQ2T60nMQNURGxLIPzq4a3AE4SLQ0cXBviQ55ul7wIYPvapeYMafFcw1Xx3q2qs1/X8200B7X2egWX/AmNED5sGfkI04Zr/C0nsVskOn8GR7UCNK+nWrAIk2gHFQMqcy9sjfwZl5b5guPZvCJhRU0o0xyIlUcVthxmASKA9gLjWpmc4mM2kEkBNp031uaYXEYKzhF7BnIT5Mhf1wobq5EWukPnlkoYCrDtUZoK5Or3CjmjO4FeDkeA565jsu/FPReGSDn6Lo0d93avthMOXYHbMBeK6eZQ51i8DGIX7EGO0WIailydQekLba5FucXvLcX3/K3qES9jpmg9nELnu026BE8t4cZ14NTjlrqq6kXURIIK60oA1ZK4wEWeJV5WGVQxEzQun0/xGMCgNd8m9sWttuATrmAqH/HWDoYL1yNO8e5cnBIa1NGka0Zvcr4rFOsAaxMmraokP2PJLbijEpyJRN5VBC1gzp9zckOa80o8Aflzl3JqByjFQcYxRDcPI0YTQolup0Uxtalr3X5pevfOppzAL0WGG0oKmjodivDwtkNfLVlCI8LlrduDmFeThVQIo0x3HcS2lqpu5k7i4no5pu3jY782CYeER56hZL5RG0v5CjZGkhA0fEGAFXw==)
    #    token : ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklraFRUSGhPZVRaYWQwUnBiakIyZDFkTFNqSkdSakJOZVVjdFdGOUtlRUp5ZUhOVlIwWjVkRGRUTFdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyYkhWemRHVnlMVzVoYldWemNHRmpaU0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUp3YjJRdGRtbGxkMlZ5TFhSdmEyVnVMV3h5TlhnNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkluQnZaQzEyYVdWM1pYSWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSmhOekk0T0dRNFppMDBZV0l5TFRRNU56Y3RZV1l4WVMwNE1qQTJZbVUyTVRWbFlqY2lMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YTJ4MWMzUmxjaTF1WVcxbGMzQmhZMlU2Y0c5a0xYWnBaWGRsY2lKOS5kQ2NrYks4MkM4eTJFU3FpNkJWcXp1V0tpcDRPV3RDWERILVV2WWp4MnBTekEzTTUxbFBvVnhWZjg1Y2Ixa3l6enVKdzBCdDRGMzYtQjZtRVY4U0p5YkpXSVA1V2ItYVktWndUTW1VV1JHVHlHVGJuZEo4eGNzd1QweVdPT1V1T2M4LWt0WVloMUs5QjUyRHFOaU5JekdsczlneUtJS0c3OHZqbnJCWEJCdWlKS2hHZG5NNGtXOTBXbF8zUDlXd1F6blFDUEpackFqUXl5WVQ1cWJVMzlZNF93T2NpWWdVeXhTenhxUE5xOWUtSlAxNVdKd0hOZUZWZmloYWxBX1RtTVpSQ0wxSHVZWFhielZxYnp4NXdTVzlSZTdBNkxqMEZYQl9SYmR3V09ra0tURWY5MUM5ZzVaN2JzYm9LTzdWWFVhcFM2QXlPa2ZNa2tyS2VQRnlIVFE=
    namespace : githubactiontestcd
argocd:
  url: https://kluster.iptime.org:7001/api/v1
  cookie: ENC(86tj2v1Mg2cQ/WeSCttOvIAV01yqft6Tne1n0IxenkubyMi0GvYn7Tl0T3Bg4usSjiGjFqJEWRysGThGXWvepm3ENzfwJIZcjb0/uaX2ZjpUeFeBJ9F/awWeq5ron2BxNIl8+cCLU8OWj0snzFczP5+XfqHLqRFCYZ+jFnX//eLyi2XHFY8Gz7X4Hti+rRbg3u5a4bNDjizvHk+5xGOWHnMN3Pt3CFhM5J9/b0q7I64GBY/gI/LdBMGvyj0fWgVwvfeVG41+HWOz5A43HOFYGhlke5KmW896gFoXIcYCid+6Vela43zyFfKPb0zHxWMkdRyL+vnc1HQ=)
#server:
#  ssl:
#    enabled: true
#    key-store: klusterweb.key
#    key-store-password: kluster!
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 4443
