spring:
  profiles:
    include: secure
  datasource:
    url: ENC(XbhnumseAaQ+WkLoTd3c8pCUUOE1qLRV01csowxFMEX6PqNOAd3adJE7wpj0b6LE6/5aqV4wSas=)
    username: ENC(zcsM8ZDJlPgE6ARZXcc30Q==)
    password: ENC(981rpExspqHwAo0RdQdfElFcAhb7heOJ)
#  datasource: # docker-compose를 사용하기 위한 설정 파일
#    url: jdbc:mysql://mysql:3306/kluster  # MySQL 호스트 및 포트
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher
jwt:
  secret: ENC(1mPRNzjXY+Uha2424+Zwk14A8rln8cRI7y+7/mbD+fDPQ7BuoOeaXYs12NxOJ66d38UQSCDTBszml6lBtf8eEQ==)
jenkins:
  url: jenkins-url
  secret-key: jenkins-secret-key
github:
  access-token: ENC(JTR6X87H+WFajH+mLgRK9bfcZogx34+fyrViAXvdazIXplkWJhOUPVzcim7i1PnQMSrai1LDV3w=)
univcert:
  api:
    key: ENC(mEC2ThOsBweDr/jxdhV+r9IZ4HB005ZTWRUfIw8U4Sfqas2tBbJ34nna2jLJhoy6)
config:
  kubernetes:
    url: https://kluster.iptime.org:6443
    token: ENC(G3awPBHJpysdl2q2N8a/xae/FVVor5WwFXjEl+evCcLQfJiFOUXvK3RTHDed5Yzqo51zctGgC3L1OOqVvWgjFnMm+2meyBjFdIL5IK1PMIdHmF5M+sTo2hUeefkpbGM6VE+wOhVLhbYPmtWehfQ0s+2I0QJJCuHnt9YQXGf2aiI+lTgFaJIJS5hXFDWLOmXrKJRQKqFZlcORBUdrG3ua28Ugl4d0ZUVEwPn6vngqF7Q3D9WYMW1yGYblfj12wN6BvszxgflsQgDTNNCBW/Jv5PoQc9hF+QF1WAD08B1s06O2ZkGfGGQPst6GyYB/Y70b/xRVtsz5xDjBFoGit9OzNTgxmiIQCbjPKG94atl6T4pCY22tLzCXs7H17yTM8otvZ2cKRY9P7Ef6N9DM9vXSvW3hzutFxD0hekGC3MsQoQdWLesywF1lSwVjlBC0vFzWo2YosMSNZW4CurdK97sQ7jpud0lKqtVisI3hrNaE+WoSvitYf4jJCflFMzfMlVJ3Dv53Gz0P+z/l5cQKgZFUggmK3CIUTxeOXjBfyNpQmpvH8HBVuvx3bVH01Ps4gBDzpq31o6G3lWuw8FbVadVVaK9eCWlUODeIciagIiFeNAJVw+FwGryajtggGw6K0kypHqFClUqfDH/JRkP1dd57WjT7nhU2KprJBze77U8yOucoTbhkm85P5Xjd4JEg2cgTKI9rBQlwu/zD4hWy/zzSwacx+3I2r44zK4M9dszDk63QLHbMHS2iBBKstp2pa9MXBeqVPM6Bk2NPdfKKI3S02ZL4rS1M+Jfwni4GPWn3rV99BD4Xa8M3ApT7MKd3Ecf/QIF+ajchLduMEVighpc3XVSzTDnJfrs28Eazz0C3PBxONhGT3uz+tvXYCCZyXujTuylnFRWNQfHAxeiPIJo8wavwKN1guh1F8wSbMif7UqMEoVhkqPZqXH0HF9++t8bJC/bTdj96SKKvDZSZtpRuwcHiIEXXn4eGd2Q6pP5rlJH7SDFClAN/kT5GWfH0EKR4fpflBd/8GS6xCCp9dcZYKFEpxNB4axbo1/jdWrOmnKy6owny3d/qpEsUx9c3SDyEYcbqRlX5dl6+Vu2ds3f2rDbD4wkC664yuw/cm8QIkSnDVPnVH8AiTmlQ4KPJ7DEwyJ/fszK97qtn0CjO3ChAdHgk4qTxVJXx4M5H125O5fDqXTy8o7CHlQ==)
    #    token : ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklraFRUSGhPZVRaYWQwUnBiakIyZDFkTFNqSkdSakJOZVVjdFdGOUtlRUp5ZUhOVlIwWjVkRGRUTFdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyYkhWemRHVnlMVzVoYldWemNHRmpaU0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUp3YjJRdGRtbGxkMlZ5TFhSdmEyVnVMV3h5TlhnNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkluQnZaQzEyYVdWM1pYSWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSmhOekk0T0dRNFppMDBZV0l5TFRRNU56Y3RZV1l4WVMwNE1qQTJZbVUyTVRWbFlqY2lMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YTJ4MWMzUmxjaTF1WVcxbGMzQmhZMlU2Y0c5a0xYWnBaWGRsY2lKOS5kQ2NrYks4MkM4eTJFU3FpNkJWcXp1V0tpcDRPV3RDWERILVV2WWp4MnBTekEzTTUxbFBvVnhWZjg1Y2Ixa3l6enVKdzBCdDRGMzYtQjZtRVY4U0p5YkpXSVA1V2ItYVktWndUTW1VV1JHVHlHVGJuZEo4eGNzd1QweVdPT1V1T2M4LWt0WVloMUs5QjUyRHFOaU5JekdsczlneUtJS0c3OHZqbnJCWEJCdWlKS2hHZG5NNGtXOTBXbF8zUDlXd1F6blFDUEpackFqUXl5WVQ1cWJVMzlZNF93T2NpWWdVeXhTenhxUE5xOWUtSlAxNVdKd0hOZUZWZmloYWxBX1RtTVpSQ0wxSHVZWFhielZxYnp4NXdTVzlSZTdBNkxqMEZYQl9SYmR3V09ra0tURWY5MUM5ZzVaN2JzYm9LTzdWWFVhcFM2QXlPa2ZNa2tyS2VQRnlIVFE=
    namespace : githubactiontestcd
argocd:
  url: https://kluster.iptime.org:7001/api/v1
  cookie: ENC(86tj2v1Mg2cQ/WeSCttOvIAV01yqft6Tne1n0IxenkubyMi0GvYn7Tl0T3Bg4usSjiGjFqJEWRysGThGXWvepm3ENzfwJIZcjb0/uaX2ZjpUeFeBJ9F/awWeq5ron2BxNIl8+cCLU8OWj0snzFczP5+XfqHLqRFCYZ+jFnX//eLyi2XHFY8Gz7X4Hti+rRbg3u5a4bNDjizvHk+5xGOWHnMN3Pt3CFhM5J9/b0q7I64GBY/gI/LdBMGvyj0fWgVwvfeVG41+HWOz5A43HOFYGhlke5KmW896gFoXIcYCid+6Vela43zyFfKPb0zHxWMkdRyL+vnc1HQ=)
#server:
#  ssl:
#    enabled: true
#    key-store: klusterweb.key
#    key-store-password: kluster!
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 4443
