spring:
  profiles:
    include: secure
  datasource:
    url: ENC(XbhnumseAaQ+WkLoTd3c8pCUUOE1qLRV01csowxFMEX6PqNOAd3adJE7wpj0b6LE6/5aqV4wSas=)
    username: ENC(zcsM8ZDJlPgE6ARZXcc30Q==)
    password: ENC(981rpExspqHwAo0RdQdfElFcAhb7heOJ)
#  datasource: # docker-compose를 사용하기 위한 설정 파일
#    url: jdbc:mysql://mysql:3306/kluster  # MySQL 호스트 및 포트
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher
jwt:
  secret: ENC(1mPRNzjXY+Uha2424+Zwk14A8rln8cRI7y+7/mbD+fDPQ7BuoOeaXYs12NxOJ66d38UQSCDTBszml6lBtf8eEQ==)
jenkins:
  url: jenkins-url
  secret-key: jenkins-secret-key
github:
  access-token: ENC(JTR6X87H+WFajH+mLgRK9bfcZogx34+fyrViAXvdazIXplkWJhOUPVzcim7i1PnQMSrai1LDV3w=)
univcert:
  api:
    key: ENC(mEC2ThOsBweDr/jxdhV+r9IZ4HB005ZTWRUfIw8U4Sfqas2tBbJ34nna2jLJhoy6)
config:
  kubernetes:
    url: https://kluster.iptime.org:6443
    token: ENC(pgLNYiLzJFIRV+caHIkVXTQpcwWQ1K9bn8BD6+MLON0idOyC+mQkcdgDHPkfhJEn+iuULfv7pkP+8kmydHJEZ0WXng6X+lroJK8+P/oO7RI2pjEdUqUIX3CfeSbp6JKqQnBhU5Ha320J4DrW7nSn4Rahg8iF7QvH8fcGffhF3Fn/9Cs1/Yt7mBIiRBlB4AYyMEDH2yPY/J1I8oNOu/jn9vJO9B35Tymc6QOXVnIKPrl+J3l4T2f66Zy/BMlgL5AEvRPiQ82KW8BZtfLXQfVdYTCf5DZ29REdanQ85MIFGUeVVa0gW3r/CKioT1SBrtITSbr16FLeANaen8K3FJ7bjm0Txkm643aMVv0mApRC68XBRNQqZI50pDS6WNLXPp/j3Th2lVzKnuTRTkhbd3LWGt0PcuNdW4jHwFFidaoytHeuITrq3O6hiyCJ1CFqGEkcWTgBsRkJwnS2+AwiOMc6d2btB4HrRcms1cE6r4Yx2PNCk59aZlMAg8kOydtNQYv7YIRcNqYWzZ57lOECX2876ygKHY6QyzrPa5E5tSGbh1HXm4uhraabk0vK2ptUagwZ9zoZKW2HJvyIUnbddC/8od59fcCOiD4m69CN/JgFxq8AMB4OKeEoZZAzti2sqbFijTT+Q+YIInSoOFIaS6NyZx1wYpZP4o5Rcg82RtywhSR8tBU1DWqwx0i1vV6zt/janzZENW+bxKkJWqAFfu5WEWkzVYnEfvFkQV89BwXaWIdf2RcH+Oji8Rznt8tg/xwG1SbAaLhtRnHp6P78wVBUS1l2QDaXx2q0lZ1hiKNxdJ293wv1o2yk8/V1+5eyt4jjEZYRYbNXxiOCek+etIniXvWy8KW4uTBVWJLkeijavdRUJaxM4C03VjvW52nV0dv+m60gK2P5Mc970/K7M2ZHX7yoVtzRlkQjW2Jyptjsds7GsFuTRo0UiT7Yr5IH086TxAONzBXvsW7JloBzRop2zClYqX8X4xgUn52FLmTlB2pLfhjJd5aXgU4wHOvH9ZgscDHTbPMNybYhUqAy1mKVDyOsA2XtrHDH1rhPqa22zJz42S1g2PSU+MSy/gnq6JH4vqIBoQcJ5Y7N96Ox2zUwGXMJaOMu3zPenXh2pX4kyAizwW+GH9TDcumB0+zh3L4RGNV1WsMRTd5lkJlXDCdEuLxxX6gHFs1inciqrawMnNI3LEUfGhIGJQ==)
    #    token : ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklraFRUSGhPZVRaYWQwUnBiakIyZDFkTFNqSkdSakJOZVVjdFdGOUtlRUp5ZUhOVlIwWjVkRGRUTFdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyYkhWemRHVnlMVzVoYldWemNHRmpaU0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUp3YjJRdGRtbGxkMlZ5TFhSdmEyVnVMV3h5TlhnNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkluQnZaQzEyYVdWM1pYSWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSmhOekk0T0dRNFppMDBZV0l5TFRRNU56Y3RZV1l4WVMwNE1qQTJZbVUyTVRWbFlqY2lMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YTJ4MWMzUmxjaTF1WVcxbGMzQmhZMlU2Y0c5a0xYWnBaWGRsY2lKOS5kQ2NrYks4MkM4eTJFU3FpNkJWcXp1V0tpcDRPV3RDWERILVV2WWp4MnBTekEzTTUxbFBvVnhWZjg1Y2Ixa3l6enVKdzBCdDRGMzYtQjZtRVY4U0p5YkpXSVA1V2ItYVktWndUTW1VV1JHVHlHVGJuZEo4eGNzd1QweVdPT1V1T2M4LWt0WVloMUs5QjUyRHFOaU5JekdsczlneUtJS0c3OHZqbnJCWEJCdWlKS2hHZG5NNGtXOTBXbF8zUDlXd1F6blFDUEpackFqUXl5WVQ1cWJVMzlZNF93T2NpWWdVeXhTenhxUE5xOWUtSlAxNVdKd0hOZUZWZmloYWxBX1RtTVpSQ0wxSHVZWFhielZxYnp4NXdTVzlSZTdBNkxqMEZYQl9SYmR3V09ra0tURWY5MUM5ZzVaN2JzYm9LTzdWWFVhcFM2QXlPa2ZNa2tyS2VQRnlIVFE=
    namespace : githubactiontestcd
argocd:
  url: https://kluster.iptime.org:7001/api/v1
  cookie: ENC(86tj2v1Mg2cQ/WeSCttOvIAV01yqft6Tne1n0IxenkubyMi0GvYn7Tl0T3Bg4usSjiGjFqJEWRysGThGXWvepm3ENzfwJIZcjb0/uaX2ZjpUeFeBJ9F/awWeq5ron2BxNIl8+cCLU8OWj0snzFczP5+XfqHLqRFCYZ+jFnX//eLyi2XHFY8Gz7X4Hti+rRbg3u5a4bNDjizvHk+5xGOWHnMN3Pt3CFhM5J9/b0q7I64GBY/gI/LdBMGvyj0fWgVwvfeVG41+HWOz5A43HOFYGhlke5KmW896gFoXIcYCid+6Vela43zyFfKPb0zHxWMkdRyL+vnc1HQ=)
#server:
#  ssl:
#    enabled: true
#    key-store: klusterweb.key
#    key-store-password: kluster!
#    key-store-type: PKCS12
#    key-alias: bns-ssl
#  port: 4443
